apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <fill your ACM arn here> #TODO: Fill it here
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    -  protocol: TCP
       port: 443
       targetPort: 5000