# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:536428703888:certificate/0bb1eb59-aa6f-43bb-9fc1-66d0844989f8
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
# spec:
#   selector:
#     app: backend
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#     - protocol: TCP
#       port: 443
#       targetPort: 5000

# ---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <your arn-acm for the domain in Route 53 here> #TODO: Fill it here
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    -  protocol: TCP
       port: 443
       targetPort: 5000